#
# NOTE - This file was designed for testing purposes only, and is not suitable
# for a production deployment.
#

version: "3.5"

networks:
  backend:
    name: stoplight_backend
    driver: bridge
  frontend:
    name: stoplight_frontend
    driver: bridge

services:
  # postgres:
  #   container_name: postgres
  #   image: sameersbn/postgresql:latest
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./stoplight-data/postgres:/var/lib/postgresql:Z
  #   environment:
  #     - DB_USER=stoplight
  #     # this has been randomized for security - this is not a real password
  #     - DB_PASS=veetah9pum9ciesee0aiWeegoh3ve2Ya
  #     - DB_NAME=stoplight
  #     - DB_EXTENSION=pg_trgm
  #     - PG_TRUST_LOCALNET=true
  #   networks:
  #     - backend
  # redis:
  #   container_name: redis
  #   image: sameersbn/redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./stoplight-data/redis:/var/lib/redis:Z
  #   environment:
  #     # this has been randomized for security - this is not a real password
  #     - REDIS_PASSWORD=toh4ahcuXoo1Pa4aeth2rai7thux
  #   networks:
  #     - backend
  gitlab:
    container_name: gitlab.stoplight.local
    image: quay.io/stoplight/gitlab:v11.0.6
    # depends_on:
    #   - postgres
    #   - redis
    ports:
      - "8000:8000"
      - "5432:5432"
      - "6379:6379"
    volumes:
      - ./stoplight-data/gitlab:/var/opt/gitlab
      # optionally store logs outside the container
      # - ./gitlab-logs:/var/log/gitlab
      - ./config/gitlab.rb:/etc/gitlab/gitlab.rb
    networks:
      - backend
      - frontend
  api:
    container_name: api.stoplight.local
    image: quay.io/stoplight/api:4.10.1
    restart: always
    depends_on:
      - gitlab
      # - postgres
      # - redis
    ports:
      - "3030:3030"
    networks:
      - backend
      - frontend
    environment:
      - NODE_ENV=production
      - SIGN_SECRET=EeK6ohSaeh6ei1oCheish6aithoedae4 # randomized
      - AUTH_SECRET=Ohgh6vaiW2koomoh1Yohphi8Lahmei5o # randomized
      - SL_JWT_SECRET=eifu5Iet0uw5aif2ohz7faiyeeCa5eob # randomized
      - SL_POSTGRES_URL=postgresql://gitlab:veetah9pum9ciesee0aiWeegoh3ve2Ya@gitlab:5432/gitlabhq_production
      - SL_APP_HOST=http://nginx.stoplight.local:8080
      - SL_API_HOST=http://nginx.stoplight.local:8080/api
      - SL_GITLAB_HOST=http://gitlab:8000
      - SL_TASKER_HOST=http://tasker.stoplight.local:9432
      - SL_PRISM_HOST=http://prism.stoplight.local:4050
      - SL_PUBS_ADMIN_URL=http://pubs.stoplight.local:9098
      - SL_REDIS_URL=redis://gitlab:6379
      - SL_COOKIE_DOMAIN=stoplight.local
  app:
    container_name: app.stoplight.local
    image: quay.io/stoplight/app:4.10.2
    restart: always
    ports:
      - "3100:3100"
    networks:
      - frontend
    environment:
      - NODE_ENV=production
      - RELEASE_STAGE=production
      - SL_APP_HOST=http://nginx.stoplight.local:8080
      - SL_API_HOST=http://nginx.stoplight.local:8080/api
      - SL_PRISM_HOST=http://nginx.stoplight.local:8080/prism
      - SL_PUBS_INGRESS=ingress.pubs.stoplight.local:9080
      - SL_PUBS_HOST=pubs.stoplight.local:9080
  nginx:
    container_name: nginx.stoplight.local
    image: nginx
    restart: always
    ports:
      - 8080:80
    networks:
      - frontend
    volumes:
      - ./nginx/next/http/default.conf:/etc/nginx/nginx.conf:ro
  # prism:
  #   container_name: prism.stoplight.local
  #   image: quay.io/stoplight/prism-multi:e2471b5
  #   restart: always
  #   ports:
  #     - "4050:4050"
  #   networks:
  #     - backend
  #     - frontend
  #   environment:
  #     - SL_API_HOST=http://api.stoplight.local:3030
  #     - SL_HOST=http://%snginx.stoplight.local:8080/prism
