# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "relativkreativ/centos-7-minimal"

  BOX_COUNT = 1
  (1..BOX_COUNT).each do |machine_id|
    config.vm.define "stoplight-#{machine_id}" do |machine|
      machine.vm.hostname = "stoplight-#{machine_id}"
      machine.vm.network "private_network", type: "dhcp"
      
      machine.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
      end

      if machine_id == BOX_COUNT
        machine.vm.provision "ansible" do |ansible|
          ansible.limit = 'all'
          ansible.playbook = "playbooks/vagrant.yml"
          ansible.extra_vars = "vars/common.yml"
          ansible.sudo = true
          ansible.host_key_checking = false
        end
      end
    end
  end
end
