markdown: kramdown
# theme: just-the-docs
# ! uncomment this when running in github
remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
title: "Stoplight Enterprise"
aux_links:
  "Find Supporting Material on Github":
    - "https://github.com/stoplightio/enterprise"
plugins:
  - jekyll-toc
toc:
  min_level: 2
  max_level: 5
